apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-JesusRamirez
  labels:
    app: mi-app-JesusRamirez
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-app-JesusRamirez
  template:
    metadata:
      labels:
        app: mi-app-JesusRamirez
    spec:
      containers:
        - name: mi-app-JesusRamirez
          image: jesusramirezgamarra/jenkins-node:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mi-app-service-JesusRamirez
spec:
  selector:
    app: mi-app-JesusRamirez
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort